# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # Maintain dependencies for Cargo
    - package-ecosystem: "cargo"
      directory: "/" # Location of package manifests
      schedule:
          interval: "weekly"
      groups:
          # Group minor and patch updates together
          minor-patch-dependencies:
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"
              exclude-patterns:
                  - "^major"
      commit-message:
          prefix: "chore"
          include: "scope"

    # Maintain dependencies for GitHub Actions
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: weekly
      groups:
          # Group minor and patch updates together for GitHub Actions
          github-actions:
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"
      commit-message:
          prefix: "ci"
          include: "scope"
