repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
          - id: fmt
            name: "rust: cargo fmt"
            description: Format files with cargo fmt.
          - id: clippy
            name: "rust: cargo clippy"
            description: Lint rust code with cargo clippy.
            args: ["--all-features", "--", "-D", "warnings"]
