[package]
name = "lazylora"
version = "0.1.0"
description = "Terminal user interface for Algorand Blockchain exploration"
authors = ["Altynbek Orumbayev <altynbek.orumbayev@makerx.com.au>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
