[package]
name = "lazylora"
version = "0.1.0"
description = "Unofficial terminal user interface for Algorand Blockchain exploration"
authors = ["Altynbek Orumbayev <aorumbayev@pm.me>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
tokio = { version = "1.36", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
